### ISSUE TITLE
Validator - new 11.30 features and earlier versions of apt.dat

### ISSUE THREAD

**Issue by legoboyvdlp** [X-Plane/xptools#11]
I may be wrong, but it seems that the validator will not prevent the export of 11.30 new linear / lighting features (for instance, red or blue lines, or ) when an earlier export target is selected? Is this correct - if so it may be worth fixing to avoid problems with invalid data that cannot be parsed with earlier versions :)

Context - I exported BWI Marshall (KBWI) as 10.50 apt.dat. However, it had unidirectional taxiway centreline lights still present in the apt.dat which were not in 10.50. This would crash TerraGear when I tried to parse the 10.50 apt.dat. 

While I think it is more TerraGear's job to update for the new 11.30, it may be worth making the validator prevent you from exporting 11.30 features to 10.50 :)
Sorry if I am missing something and thank you for this awesome tool.

**Comment by meikelm** [comment]
In X-plane those new linetype number are legal to use in older versions - they cleanly ignore them.

WED 2.2 also does translate most newly-added linestyles into their closest old-style couterparts when the export target is older than XP11.30.
