### ISSUE TITLE
Building 'libs' fails on Ubuntu

### ISSUE THREAD

**Issue by barf** [X-Plane/xptools#13]
Hello. 

Following the instructions at https://developer.x-plane.com/code/ I am unable to build the 'libs' component of xptools on Ubuntu 20.04 after installing the listed prerequisite packages - with the exception of Qt4 because that's been deprecated (and I want to look into porting WED to Qt5).

Steps to reproduce:
1. git clone https://github.com/X-Plane/xptools
2. cd xptools
3. git submodule update --init
4. cd libs
5. make

Output tail:
```common.copy /home/barf/X-Plane/libboost_system.a
common.copy /home/barf/X-Plane/libboost_thread.a
...updated 11358 targets...
/bin/sh: 1: cd: can't cd to local/lib
make: *** [Makefile:391: local/lib/.xpt_boost] Error 2```

**Comment by meikelm** [comment]
We have a Qt5 branch "- try "wed_qt5_dev".
But we can't take that into master right now until all dev's and the compile farm have been upgraded to that as well. We might even happen that Qt get's rather dropped entirely fro something less complex.

**Comment by mroe1** [comment]
> We might even drop Qt entirely for something less `complex.`
uh oh , i standing by for the less complex part ;)

**Comment by barf** [comment]
Sorry to post on a closed bug, but I think I was completely mistaken about Qt, and this might be an escaping issue for space characters in the build scripts instead.
