### ISSUE TITLE
Suggestion: add 7zip compression support for DSFTool

### ISSUE THREAD

**Issue by BigKananga** [X-Plane/xptools#16]
Would it be possible to add 7zip support for DSFTool? The command line tools 15-3 doesn't seem to support it. E.g. when dragging  a HD Mesh v4 dsf into XGrinder, you get an empty txt file, because you have to extract the file first.

It would be also nice if a compression option in XGrinder for dsf files would be possible.

**Comment by meikelm** [comment]
Please use a current version of DSFTool - this feature was added a while ago already.

**Comment by BigKananga** [comment]
Where can I get the latest official final version? I'm downloading from here:
https://developer.x-plane.com/tools/xptools/

**Comment by mroe1** [comment]
https://developer.x-plane.com/2020/09/command-line-tools-beta-builds/
