### ISSUE TITLE
Please disable "autozoom to selection" in WED

### ISSUE THREAD

**Issue by DiscoNova** [X-Plane/xptools#30]
When I select something and click on e.g. some group, I don't want WED to automatically zoom out to whatever the heck I have clicked.

Whenever WED does that, I need to refocus myself into what I was doing - and this happens more often than necessary.

Very annoying.

**Comment by mroe1** [comment]
Hello DiscoNova,
In 'Menu->File->Preferences'  uncheck 'Moderator mode' and your issue is gone. 
Btw.: This mode is not set by default and you have certainly opt it in sometime in the past.

**Comment by mroe1** [comment]
no issue

**Comment by DiscoNova** [comment]
Yes... I do remember turning the mode on at some point, but had thought it'd only give validation warnings for deprecated resources etc. ... heh, never thought that'd be the culprit for my woes :D
