### ISSUE TITLE
Libs not compiling

### ISSUE THREAD

**Issue by pniang** [X-Plane/xptools#4]
Hello!

The following is producing an error. 
git submodule update --init
cd libs
make
Error: make: *** [local/lib/.xpt_libgeotiff] Error 1

I read the notes about the cmake version, but I would like to know why. Can you make it work with the latest versions of cmake and xcode. I am using cmake version 3.8.1 and xcode version 8.2.1.

Thank you!

**Comment by meikelm** [comment]
We use https://gateway.x-plane.com/bugs/view exclusively for bug reporting.
