### ISSUE TITLE
Spanish (or other languages) traduction for WED´s manual.

### ISSUE THREAD

**Issue by mirkojovic** [X-Plane/xptools#7]
How I can contribute in the translation of WED`s Manual? I copied all english manual to Markdown format. Slowly, i will going to translate it. But, if this translation can be in the repositorie, maybe de translation could be faster.

Thanks

Mirko

**Comment by meikelm** [comment]
We are not using github for communication - please use http://gateway.x-plane.com

And the WED manual isn't on github either, nor do we want to put it there. Please contact jennifer@x-plane.com to see what to do.
